spring.application.name=demoSpringBootAngular
spring.datasource.url=jdbc:postgresql://localhost:5432/Yt2_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
