spring.application.name=demoSpringBootAngular
spring.datasource.url=jdbc:postgresql://localhost:5432/Yt2_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-request-size=500MB
spring.servlet.multipart.max-file-size=505MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=500MB
spring.jpa.show-sql=true
app.jwt.secret=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
app.jwt.expirationMs=86400000
logging.level.org.springframework.security=DEBUG
